version: "3.8"
services:
  frontend:
    build: ./frontend
    image: hussaino/coursework-app-frontend:latest
    container_name: coursework-app-frontend
    ports:
    - target: 5000
      published: 80
  backend:
    build: ./backend
    image: hussaino/coursework-app-backend:latest
    container_name: coursework-app-backend
    environment:
      DATABASE_URI:
      CREATE_SCHEMA:
    ports:
    - target: 5000
      published: 5000
